apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  vault-token: aHZzLjByc0wxWVo3U2FHMWVmWEttQ3ZxMDVLcw==
  config-server-salt: ZGV2X3NhbHQ=
  config-server-encryption-key: ZGV2X2tleQ==
