spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    locations: filesystem:/app/database
    enabled: true
    clean-disabled: true
    schemas: rgts, batch_schema

eureka:
  client:
    enabled: true