server:
  port: 8085

spring:
  application:
    name: notification-service

logging:
  package: com.rahim.notificationservice
  level:
    com.rahim.notificationservice: DEBUG
    org.springframework: ERROR
    org.hibernate: ERROR
    root: WARN
  file:
    name: opt/logs/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"