server:
  port: 8081

spring:
  application:
    name: user-service

logging:
  package: com.rahim.userservice
  level:
    com.rahim.userservice: DEBUG
    org.springframework: ERROR
    org.hibernate: ERROR
    root: WARN
  file:
    name: opt/logs/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"

management:
  zipkin:
    service:
      name: ${spring.application.name}