spring:
  cloud:
    config:
      server:
        vault:
          enabled: false
    vault:
      enabled: false
      kv:
        enabled: false
        backend: kv
        application-name: config-server
      host: vault.vault.svc.cluster.local
      port: 8200
      scheme: http
      authentication: kubernetes
      kubernetes:
        role: vault_k8
