spring:
  cloud:
    vault:
      enabled: false
      kv:
        enabled: true
        backend: kv
        application-name: config-server
      host: vault.vault.svc.cluster.local
      port: 8200
      scheme: http
      authentication: kubernetes
      kubernetes:
        role: vault_k8