spring:
  cloud:
    vault:
      enabled: true
      kv:
        enabled: true
        backend: kv
        application-name: config-server
      authentication: kubernetes
      kubernetes:
        role: vault_k8
      uri: http://vault.vault.svc.cluster.local:8200