spring:
  cloud:
    vault:
      enabled: true
      kv:
        enabled: false
        backend: kv
        application-name: config-server
      host: vault.vault
      port: 8200
      scheme: http
      authentication: kubernetes
      kubernetes:
        role: vault_k8
