eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.rahim.batchservice: DEBUG
    org.springframework: ERROR
    root: WARN
  package: com.rahim.batchservice

management:
  tracing:
    sampling:
      probability: 1.0

processing:
  chunk-size: 500

server:
  port: 8086

spring:
  application:
    name: account-service
  datasource:
    default-schema: batch_schema
  output:
    ansi:
      enabled: always
