eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.rahim.emailservice: DEBUG
    org.springframework: ERROR
    root: WARN
  package: com.rahim.emailservice

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8083

spring:
  application:
    name: email-service
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(oyWkyXN9/0TvP+Q34QlJOhjpqRzG6u+No+Eguyh5mlahJS12s0ApEeWjaaRUj+cbuUTGnVbon0i3hBeAbXWE6g==)
    password: ENC(eLQ7/j7ZCkRazmtM1ULeoS2A3Sms9/KI1uKHAipXmf3Z4f1qmfAZ+pRus3/WylCNF9ca92hp+zFSR2TGzFB6ww==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
