eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.rahim.investmentservice: DEBUG
    org.springframework: ERROR
    root: WARN
  package: com.rahim.investmentservice

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8087

spring:
  application:
    name: investment-service
  output:
    ansi:
      enabled: always
