server:
  port: 8082

spring:
  application:
    name: scheduler-service
  task:
    scheduling:
      time-zone: UTC

cron:
  job:
    initial-delay: 100
    db-refresh-interval: 60000

logging:
  package: com.rahim.schedulerservice
  level:
    com.rahim.schedulerservice: DEBUG
    org.springframework: ERROR
    org.hibernate: ERROR
    root: WARN
  file:
    name: logs/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"