replicaCount: 1

image:
  repository: rahimahmed/database
  tag: latest
  pullPolicy: IfNotPresent

springProfilesActive: qa

container:
  name: database-service

configMap:
  appConfig:
    # Config Map name created in config-server
    name: rgts-appconfig

job:
  backoffLimit: 4