spring:
  application:
    name: scheduler-service
  config:
    import: "configserver:http://localhost:8088"
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/gold
    username: postgres
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      user-deletion: user-deletion-topic