replicaCount: 1

image:
  repository: rahimahmed/discovery-service
  tag: latest
  pullPolicy: Always

container:
  name: discovery-service

service:
  name: discovery-service
  port: 8761

configMap:
  discoveryService:
    name: rgts-discoveryservice
    data:
      discoverySvc: "discovery-service.qa.svc.cluster.local"
      discoveryPort: "8761"
