apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.appConfig.name }}
  labels:
    app: rgts
  annotations:
    description: Configuration for Discovery Service
data:
  kafkaBroker: {{ .Values.configMap.appConfig.data.kafkaBroker | quote }}
  pythonApiSvc: {{ .Values.configMap.appConfig.data.pythonApiSvc | quote }}
