apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.appConfig.name }}
  labels:
    app: rgts
  annotations:
    description: Configuration for Application
data:
  configSvcUri: {{ .Values.configMap.appConfig.data.configSvcUri | quote }}
  discoverySvcUri: {{ .Values.configMap.appConfig.data.discoverySvcUri | quote }}
  kafkaBroker: {{ .Values.configMap.appConfig.data.kafkaBroker | quote }}
  pythonApiSvcUri: {{ .Values.configMap.appConfig.data.pythonApiSvcUri | quote }}