apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-config-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-config-server
  template:
    metadata:
      labels:
        app: spring-config-server
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vault-token
            - name: DISCOVERY_SVC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: DISCOVERY_SVC
            - name: DISCOVERY_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: DISCOVERY_PORT
            - name: PYTHON_API_SVC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: PYTHON_API_SVC
            - name: CONFIG_SERVER_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: config-server-encryption-key
            - name: CONFIG_SERVER_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: config-server-salt
