apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-config-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-config-server
  template:
    metadata:
      labels:
        app: spring-config-server
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java", "-jar", "/app/config-server.jar"]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfilesActive }}
            - name: DISCOVERY_SVC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.appConfig.name }}
                  key: discoverySvcUri
            - name: PYTHON_API_SVC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.appConfig.name }}
                  key: pythonApiSvcUri
            - name: CONFIG_SERVER_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.configServer.name }}
                  key: encryptRsaKey
            - name: CONFIG_SERVER_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.configServer.name }}
                  key: encryptRsaSalt
