apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.configServer.name }}
type: Opaque
data:
  encryptRsaKey: {{ .Values.secret.configServer.data.encryptRsaKey | b64enc | quote}}
  encryptRsaSalt: {{ .Values.secret.configServer.data.encryptRsaSalt | b64enc | quote}}
