replicaCount: 1

image:
  repository: rahimahmed/python-api
  tag: latest
  pullPolicy: Always

container:
  name: python-api

service:
  name: python-api
  port: 8000

configMap:
  pythonApi:
    name: rgts-pythonconfig
  data:
    dbHost: postgresql.qa.svc.cluster.local
    dbName: gold
    dbPort: 5432
    kafkaBootstrapServers: localhost:9092
    kafkaTopic: gold-price-stream

secret:
  pythonApi:
    name: rgts-pythonsecret
    data:
      dbUsername: postgres
      dbPassword: password
      encryptionKey: changeMe