replicaCount: 1

image:
  repository: rahimahmed/database
  tag: latest
  pullPolicy: Always

springProfilesActive: qa

container:
  name: database-service

configMap:
  appConfig:
    # Config map name value to be updated with one found in discovery-service/values.yaml
    name: rgts-appconfig
    data:
      configSvcUri: configSvcUri

job:
  backoffLimit: 4