replicaCount: 1

image:
  repository: rahimahmed/eureka-server
  tag: latest
  pullPolicy: Always

springProfilesActive: qa

container:
  name: eureka-server

service:
  name: eureka-server
  port: 8761