global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Gateway Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
           application: "Gateway Service"
           
  - job_name: 'Account Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
           application: "Account Microservice"
           
  - job_name: 'Scheduler Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
           application: "Scheduler Microservice"
           
  - job_name: 'Email Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
           application: "Email Microservice"

  - job_name: 'Pricing Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
           application: "Pricing Microservice"
           
  - job_name: 'Notification Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
           application: "Notification Microservice"
           
  - job_name: 'Batch Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
        labels:
           application: "Batch Microservice"
           
  - job_name: 'Investment Service Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
        labels:
           application: "Investment Microservice"
           
  - job_name: 'Config Server Input'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8888']
        labels:
           application: "Config Server"
           