spring:
  application:
    name: user-service
  config:
    import: "configserver:http://localhost:8088"
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/gold
    username: postgres
    password: password