apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java", "-jar", "/app/discovery-service.jar"]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfilesActive }}