apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", {{ .Values.service.port }}]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DEPLOYMENT_TYPE
              value: cloud
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.pythonApi.name }}
                  key: encryptionKey
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.pythonApi.name }}
                  key: dbHost
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.pythonApi.name }}
                  key: dbName
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.pythonApi.name }}
                  key: dbPort
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.pythonApi.name }}
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.pythonApi.name }}
                  key: dbPassword
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.pythonApi.name }}
                  key: kafkaBootstrapServers
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.pythonApi.name }}
                  key: kafkaTopic