apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.pythonApi.name }}
type: Opaque
data:
  dbUsername: {{ .Values.secret.pythonApi.data.dbUsername | b64enc}}
  dbPassword: {{ .Values.secret.pythonApi.data.dbPassword | b64enc}}
  encryptionKey: {{ .Values.secret.pythonApi.data.encryptionKey | b64enc}}
