kafka:
  bootstrap_servers: localhost:9092
  group_id: gold-price-api
  auto_offset_reset: earliest
  topic: gold-price-stream

app:
  host: localhost
  port: 8000

database:
  name: gold
  host: localhost
  port: 5432
  username: gAAAAABmJBjc3WeldeQB062Ovq7zcVilrnoS6nQWECFJg7Ww3nEVOiKsXSkcSQvRNlKDdHys82PQr6EPn-nfTQ2Xs3N-pzFxIQ==
  password: gAAAAABmJBjciMSo6ZH0vVX37iBNHjmc5V3_vJWEBKXbgxHB_RJgDg30aFfVfr_5uNIIFlo7mtJ7gVoP7Hp-VFV7JQ24FxLxsw==

vault:
  url: http://localhost:8200
  token: hvs.zLyPID1klP2OFLBsk5hwhFUg
  backend-path: kv/data/my-app
