kafka:
  bootstrap_servers: localhost:9092
  group_id: gold-price-api
  auto_offset_reset: earliest
  topic: gold-price-stream

app:
  host: localhost
  port: 8000

database:
  name: gold
  host: localhost
  port: 5432
  username: gAAAAABmI_1MizmAFy1DQ0O_18k4hSwt0AKeZA8MN34pJylkXSzOk4VvWz1ss7L-VQMStCx6SzKxV0Ywzb_zyzu8j36maLEocg==
  password: gAAAAABmI_1MFMaeOXwhKEHGUdTZK8A6co232KK9qie18e_T5CpF_cssiGlXN3Pl1UMjBeeFixn3al1NTNFzPAF9ry1vZnsV6g==
