# Environment and Version
environment: qa
version: 1.0.0

# Replica Configuration
replicaCount: 1

###########################################
# Docker Image Configuration
image:
  repository: rahimahmed/email-service
  tag: latest
  pullPolicy: Always

###########################################
# Spring Profile Configuration
springProfilesActive: "qa"

###########################################
# Container Configuration
container:
  name: email-service

###########################################
# Kubernetes Service Configuration
service:
  name: email-service
  port: 8083

###########################################
# Readiness Probe Configuration
readinessProbe:
  healthCheckPort: 8083
  initialDelaySeconds: 20
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 10
  timeoutSeconds: 5

###########################################
# Liveness Probe Configuration
liveness:
  healthCheckPort: 8083
  initialDelaySeconds: 20
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 10
  timeoutSeconds: 5

###########################################
# Resource Limits and Requests
resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m