eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/account-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg%n"

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081

spring:
  application:
    name: account-service
  hazelcast:
    config: classpath:hazelcast-default.yaml
  output:
    ansi:
      enabled: always
