spring:
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    url: ${db-url}
    username: ENC(CbB4+oU4KgU8ehQ8WF1a5X8KQ4/54U5CCUNkMeSvxhQbVGR/Fd/V2lqRfxh3Ipwt)
    password: ${db-password}
  kafka:
    bootstrap-servers: localhost:9092
jasypt:
  encryptor:
    password: password1
  #password: ${jasypt.encryptor.password}
management:
  endpoints:
    web:
      exposure:
        include: env, health
