spring:
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/gold
    username: ${db-username}
    password: ${db-password}
  kafka:
    bootstrap-servers: localhost:9092