spring:
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  kafka:
    bootstrap-servers: localhost:9092
jasypt:
  encryptor:
    password: password1
  #password: ${jasypt.encryptor.password}
management:
  endpoints:
    web:
      exposure:
        include: env, health
