eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.rahim.accountservice: DEBUG
    org.springframework: ERROR
    root: WARN
  package: com.rahim.authenticationservice

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8089

spring:
  application:
    name: authentication-service
