server:
  port: 8086

spring:
  datasource:
    default-schema: batch_schema

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

processing:
  chunk-size: 500