server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email-address}
    password: ${email-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true