spring:
  application:
    name: gateway-service
  output:
    ansi:
      enabled: always

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: WARN
    com:
      rahim:
        gatewayservice: INFO
    org:
      springframework: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway-service.log
  color:
    enabled: true
