eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.rahim.gatewayservice: DEBUG
    org.springframework: ERROR
    root: WARN
  package: com.rahim.gatewayservice

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8080

spring:
  application:
    name: gateway-service
  output:
    ansi:
      enabled: always
