hazelcast:
  network:
    port:
      auto-increment: true
      port-count: 100
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        members:
          - 127.0.0.1:5701
          - 127.0.0.1:5702
