spring:
  application:
    name: pricing-service
  output:
    ansi:
      enabled: always

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

gold-price-api:
  url: http://localhost:8000/api/v1
  endpoint: uk-investing

logging:
  level:
    root: WARN
    com:
      rahim:
        pricingservice: INFO
    org:
      springframework: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: logs/pricing-service.log
  color:
    enabled: true