eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/pricing-service.log
  level:
    com:
      rahim:
        pricingservice: DEBUG
    org:
      springframework: ERROR
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"

server:
  port: 8084

spring:
  application:
    name: pricing-service
