cron:
  job:
    initial-delay: 100
    db-refresh-interval: 60000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  color:
    enabled: true
  file:
    name: logs/scheduler-service.log
  level:
    com:
      rahim:
        schedulerservice: TRACE
    org:
      springframework: ERROR
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082

spring:
  application:
    name: scheduler-service
  output:
    ansi:
      enabled: always
  task:
    scheduling:
      time-zone: UTC
