cron:
  job:
    initial-delay: 100
    db-refresh-interval: 60000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.rahim.schedulerservice: DEBUG
    org.springframework: ERROR
    root: WARN
  package: com.rahim.schedulerservice

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082

spring:
  application:
    name: scheduler-service
  output:
    ansi:
      enabled: always
  task:
    scheduling:
      time-zone: UTC
