spring:
  cloud:
    vault:
      enabled: true
      kv:
        enabled: true
        application-name: config-server
        backend: kv
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: hvs.KzuC6RcupYAMDJOVawa64Dsk
#      ssl:
#        key-store: file://{location}
#        key-store-password: password
#        trust-store: file://{location}
#        trust-store-password: password