apiVersion: v1
name: config-server
description: A Helm chart for deploying the Spring Cloud Config Server in Kubernetes
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - config
  - microservices
  - kubernetes
maintainers:
  - name: Rahim Ahmed
    email: rahim1605@gmail.com
sources:
  - https://github.com/ItsRahim/gold-tracker-project/tree/main/config-server