replicaCount: 1

image:
  repository: rahimahmed/config-server
  tag: latest
  pullPolicy: Always

container:
  name: config-server

service:
  name: config-server
  port: 8888

configMaps:
  vault: vault-config
  discovery: discovery-config
  app: app-config

secrets:
  name: config-server-secrets