replicaCount: 1

image:
  repository: rahimahmed/config-server
  tag: latest
  pullPolicy: Always

springProfilesActive: native,qa

container:
  name: config-server

service:
  name: config-server
  port: 8888

configMap:
  appConfig:
    name: rgts-appconfig
    data:
      # To be updated with the broker url of kafka deployed in K8
      kafkaBroker: "localhost:9092"
      # To be updated with the svc name of python api deployed in K8
      pythonApiSvcUri: "http://python-service.default.svc.cluster.local:8000"
      configSvcUri: "http://config-server.default.svc.cluster.local:8888"
  discoveryService:
    # Config map name value to be updated with one found in discovery-service/values.yaml
    name: rgts-discoveryservice
    data:
      # These values are references to the keys in the discovery service config map
      svc: discoverySvc
      port: discoveryPort

secret:
  configServer:
    name: rgts-configserver
    data:
      encryptRsaKey: changeMe
      encryptRsaSalt: letMeIn