replicaCount: 1

image:
  repository: rahimahmed/config-server
  tag: latest
  pullPolicy: IfNotPresent

container:
  name: config-server

service:
  name: config-server
  port: 8888

configMap:
  name: app-config
  keys:
    - DISCOVERY_SVC
    - DISCOVERY_PORT
    - PYTHON_API_SVC

secrets:
  name: secrets
  keys:
    - vault-token
    - config-server-encryption-key
    - config-server-salt
