replicaCount: 1

image:
  repository: rahimahmed/config-server
  tag: latest
  pullPolicy: Always

springProfilesActive: "native,qa"

container:
  name: config-server

service:
  name: config-server
  port: 8888

configMap:
  appConfig:
    name: rgts-appconfig
    data:
      # Broker URL of Kafka deployed in Kubernetes
      kafkaBroker: "localhost:9092"
      # Service name of Python API deployed in Kubernetes
      pythonApiSvcUri: "http://python-service.default.svc.cluster.local:8000"

secret:
  configServer:
    name: rgts-configserver
    data:
      encryptRsaKey: changeMe
      encryptRsaSalt: letMeIn