name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [ "account-service" ]
        #folder: [ "account-service", "config-server", "custom-api", "database", "discovery-service", "email-service", "gateway-service", "investment-service", "notification-service", "pricing-service", "scheduler-service" ]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t rahimahmed/${{ matrix.folder }} -f ${{ matrix.folder }}/Dockerfile .

      - name: Push the Docker image
        run: docker push rahimahmed/${{ matrix.folder }}
